name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9.11.0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C apps/web tsc --noEmit
      - run: pnpm -C apps/web prisma generate
      - run: pnpm -C apps/web lint || echo "lint step optional for now"
      - run: pnpm -C apps/web build
